
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ummug
 */
public class tablo extends javax.swing.JFrame {

    /**
     * Creates new form tablo
     */
    DefaultTableModel tablo  = new DefaultTableModel();
    
    
    public tablo() {
        initComponents();
        gösterge_tablosu.setModel(tablo);
        tablo.setColumnIdentifiers(new String[] {"Ad","Soyad","Numara","Plaka","Saat"});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sys_ad = new javax.swing.JTextField();
        sys_soyad = new javax.swing.JTextField();
        sys_numara = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sys_plaka = new javax.swing.JTextField();
        sys_giriş_saati = new javax.swing.JTextField();
        btn_giriş = new javax.swing.JButton();
        btn_iptal = new javax.swing.JButton();
        btn_cıkış = new javax.swing.JButton();
        btn_sonlandır = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gösterge_tablosu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Girişi");
        setLocation(new java.awt.Point(200, 100));

        jLabel1.setText("Müşteri Adı :");

        jLabel2.setText("Soyad : ");

        jLabel3.setText("İletişim Numarası :");

        jLabel4.setText("Giriş Saat :");

        sys_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sys_adActionPerformed(evt);
            }
        });

        jLabel5.setText("Araç Plakası : ");

        btn_giriş.setBackground(new java.awt.Color(204, 204, 204));
        btn_giriş.setText("Kaydet");
        btn_giriş.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_giriş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girişActionPerformed(evt);
            }
        });

        btn_iptal.setBackground(new java.awt.Color(204, 204, 204));
        btn_iptal.setText("İptal");
        btn_iptal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });

        btn_cıkış.setBackground(new java.awt.Color(204, 204, 204));
        btn_cıkış.setText("Çıkış Yap");
        btn_cıkış.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cıkış.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cıkışActionPerformed(evt);
            }
        });

        btn_sonlandır.setBackground(new java.awt.Color(204, 204, 204));
        btn_sonlandır.setText("Sistemi Sonlandır");
        btn_sonlandır.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sonlandır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sonlandırActionPerformed(evt);
            }
        });

        gösterge_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gösterge_tablosu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_sonlandır, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sys_numara, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sys_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(sys_ad))
                            .addComponent(sys_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sys_giriş_saati, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_cıkış, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(btn_iptal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_giriş, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(sys_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sys_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sys_numara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sys_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sys_giriş_saati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_giriş)
                        .addGap(18, 18, 18)
                        .addComponent(btn_iptal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cıkış)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sonlandır))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sys_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sys_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sys_adActionPerformed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
        sys_ad.setText("");
        sys_soyad.setText("");
        sys_numara.setText("");
        sys_plaka.setText("");
        sys_giriş_saati.setText("");
    }//GEN-LAST:event_btn_iptalActionPerformed

    private void btn_cıkışActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cıkışActionPerformed
        double hesap;
        String giriş_saati = JOptionPane.showInputDialog("Giriş Saati");
        String cıkış_saati = JOptionPane.showInputDialog("Çıkış Saati");
        double grş_st =Double.parseDouble(giriş_saati);
        double çkş_st = Double.parseDouble(cıkış_saati);
        double saat_farkı = (çkş_st - grş_st);
        hesap = saat_farkı * 15;
        JOptionPane.showMessageDialog(rootPane,"Tutar : "+ String.valueOf(hesap));
        tablo.removeRow(gösterge_tablosu.getSelectedRow());
        
    }//GEN-LAST:event_btn_cıkışActionPerformed

    private void btn_girişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girişActionPerformed
        String ad = sys_ad.getText();
        String soyad =sys_soyad.getText();
        String numara = sys_numara.getText();
        String plaka = sys_plaka.getText();
        String saat = sys_giriş_saati.getText();
        sys_ad.setText("");
        sys_soyad.setText("");
        sys_numara.setText("");
        sys_plaka.setText("");
        sys_giriş_saati.setText("");
        String save_message ="Kayıt Tamamlandı";
        JOptionPane.showMessageDialog(rootPane, save_message);
        tablo.addRow(new String[] {ad,soyad,numara,plaka,saat});
    }//GEN-LAST:event_btn_girişActionPerformed

    private void btn_sonlandırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sonlandırActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sonlandırActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cıkış;
    private javax.swing.JButton btn_giriş;
    private javax.swing.JButton btn_iptal;
    private javax.swing.JButton btn_sonlandır;
    private javax.swing.JTable gösterge_tablosu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sys_ad;
    private javax.swing.JTextField sys_giriş_saati;
    private javax.swing.JTextField sys_numara;
    private javax.swing.JTextField sys_plaka;
    private javax.swing.JTextField sys_soyad;
    // End of variables declaration//GEN-END:variables
}
